export const CARREGAR_PRODUTOS_FACTORY = 'CARREGAR_PRODUTOS_FACTORY'

export const CRIAR_VENDA_FACTORY = 'CRIAR_VENDA_FACTORY'

export const CRIAR_PRODUTOS_VENDAS_FACTORY = 'CRIAR_PRODUTOS_VENDAS_FACTORY'